name: CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Prepare version 
        uses: bhowell2/github-substring-action@v1.0.0
        id: ver
        with:
          value: ${{ github.ref }}
          index_of_str: "refs/tags/v"

      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/Codecagon.Tools.AzureFunctions.OpenAPIGenerator/Codecagon.Tools.AzureFunctions.OpenAPIGenerator.csproj
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: Codecagon.Tools.AzureFunctions.OpenAPIGenerator
          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          VERSION_STATIC: ${{ steps.ver.outputs.substring }}
          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false
          NUGET_KEY: ${{ secrets.NUGET_SECRET }}
